import { Cog, Calendar, Mail, Compass, GitMerge, Combine, Beaker, Workflow, Merge, GitPullRequest, Search, Replace, Bot, Waypoints, Terminal, BrainCircuit, Webhook } from 'lucide-react';
import type { Extension } from './types';

export const extensions: Extension[] = [
  {
    id: 'code-executor',
    name: 'Code Executor',
    version: '1.0.0',
    description: 'Execute code snippets in a sandboxed environment.',
    icon: Cog,
    enabled: true,
    connected: false,
  },
  {
    id: 'calendar',
    name: 'Calendar',
    version: '1.0.0',
    description: 'Integrate with your calendar to manage events.',
    icon: Calendar,
    enabled: false,
    connected: false,
  },
  {
    id: 'email',
    name: 'Email',
    version: '1.0.0',
    description: 'Connect your email to read and send messages.',
    icon: Mail,
    enabled: false,
    connected: false,
  },
  {
    id: 'web-browser',
    name: 'Web Browser',
    version: '1.0.0',
    description: 'Browse the web to find information.',
    icon: Compass,
    enabled: true,
    connected: true,
  },
  {
    id: 'git-integration',
    name: 'Git Integration',
    version: '1.2.0',
    description: 'Perform Git operations like commit, push, and pull.',
    icon: GitMerge,
    enabled: true,
    connected: true,
  },
  {
    id: 'api-tester',
    name: 'API Tester',
    version: '0.9.0',
    description: 'Test API endpoints with a simple interface.',
    icon: Beaker,
    enabled: true,
    connected: false,
  },
  {
    id: 'workflow-builder',
    name: 'Workflow Builder',
    version: '1.5.0',
    description: 'Create and automate complex workflows.',
    icon: Workflow,
    enabled: false,
    connected: false,
  },
  {
    id: 'request-resolver',
    name: 'Request Resolver',
    version: '1.1.0',
    description: 'Resolve and manage incoming requests.',
    icon: GitPullRequest,
    enabled: true,
    connected: true,
  },
  {
    id: 'search-engine',
    name: 'Search Engine',
    version: '2.0.0',
    description: 'A powerful search engine to find anything.',
    icon: Search,
    enabled: true,
    connected: true,
  },
  {
    id: 'text-replacer',
    name: 'Text Replacer',
    version: '1.3.0',
    description: 'Replace text in files and documents.',
    icon: Replace,
    enabled: false,
    connected: false,
  },
  {
    id: 'ai-assistant',
    name: 'AI Assistant',
    version: '3.0.0',
    description: 'An intelligent assistant to help with various tasks.',
    icon: Bot,
    enabled: true,
    connected: true,
  },
  {
    id: 'pathfinder',
    name: 'Pathfinder',
    version: '1.8.0',
    description: 'Find the best path for your data and processes.',
    icon: Waypoints,
    enabled: false,
    connected: false,
  },
  {
    id: 'command-prompt',
    name: 'Command Prompt',
    version: '1.0.0',
    description: 'A terminal for executing commands.',
    icon: Terminal,
    enabled: true,
    connected: true,
  },
  {
    id: 'deep-thought',
    name: 'Deep Thought',
    version: '2.5.0',
    description: 'An AI for deep thinking and analysis.',
    icon: BrainCircuit,
    enabled: false,
    connected: false,
  },
  {
    id: 'merger',
    name: 'Merger',
    version: '1.6.0',
    description: 'Merge different data sources into one.',
    icon: Merge,
    enabled: true,
    connected: false,
  },
  {
    id: 'combiner',
    name: 'Combiner',
    version: '1.4.0',
    description: 'Combine multiple elements into a single unit.',
    icon: Combine,
    enabled: false,
    connected: false,
  },
  {
    id: 'developer-tools',
    name: 'API & Developer Access',
    version: '1.0.0',
    description: 'Public API for developers and webhooks for event-driven workflows.',
    icon: Webhook,
    enabled: false,
    connected: false,
  },
];
